FROM kubeflownotebooks/notebook-server-jupyter:e3153c9

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

COPY requirements-cuda.txt .
RUN python3 -m pip install -r \
    requirements-cuda.txt --quiet --no-cache-dir \
    -f https://download.pytorch.org/whl/torch_stable.html \
    && rm -f requirements-cuda.txt
