FROM kubeflownotebooks/notebook-server-jupyter:e3153c9

COPY requirements-cpu.txt .
RUN python3 -m pip install -r \
    requirements-cpu.txt --quiet --no-cache-dir \
    && rm -f requirements-cpu.txt
