name: Notebook Base

on:
  push:
    branches: [ master ]
    tags:
    - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:  
  build-notebooks:
    name: Build and push notebook images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfiles: [$(CHANGED_FILES)]
    steps:
    -
        name: Checkout
        uses: actions/checkout@v2
    - 
      name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "CHANGED_FILES=$(for changed_folder in $(dirname $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }}) | sort -u); do find $changed_folder -name "*Dockerfile"; done | sed 's/^\|$/"/g'|paste -sd, -)" >> $GITHUB_ENV
    - name: test
      run: |
        echo ${{matrix.dockerfiles}}
    # - 
    #   name: Create a GitHub release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.tag_version.outputs.new_tag }}
    #     release_name: Release ${{ steps.tag_version.outputs.new_tag }}
    #     body: ${{ steps.tag_version.outputs.changelog }}
    # -
    #   name: Docker meta
    #   id: meta
    #   uses: crazy-max/ghaction-docker-meta@v2
    #   with:
    #     # list of Docker images to use as base name for tags
    #     images: |
    #       kubeflownotebooks/base
    #     # ghcr.io/davidspek/kubeflownotebook-base
    #     # generate Docker tags based on the following events/attributes
    #     tags: |
    #       type=ref,event=branch
    #       type=ref,event=pr
    #       type=semver,pattern={{raw}},value=${{ steps.tag_version.outputs.new_tag }}
    #       type=semver,pattern={{major}}.{{minor}}
    #       type=semver,pattern={{major}}
    #       type=sha
    # -
    #   name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    # -
    #   name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # -
    #   name: Login to DockerHub
    #   if: github.event_name != 'pull_request'
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # #-
    # #  name: Login to GHCR
    # #  if: github.event_name != 'pull_request'
    # #  uses: docker/login-action@v1
    # #  with:
    # #    registry: ghcr.io
    # #    username: ${{ github.repository_owner }}
    # #    password: ${{ secrets.MY_GITHUB_TOKEN }}
    # -
    #   name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./base
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    
