name: Notebook Base

on:
  push:
    branches: [ master ]
    tags:
    - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:  
  build-matrix:
    name: Build and push notebook images
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        id: set-matrix
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # No shallow clone, we need all history
    - run: echo "::set-output name=matrix::{\"include\":[$(for changed_folder in $(dirname $(git diff --name-only ${{ github.event.before }}..${{ github.event.after }}) | sort -u); do find $changed_folder -name "*Dockerfile"; done | sed 's/^\|$/"/g'|paste -sd, -)]}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  test-matrix:
    name: Build and push notebook images
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
    steps:
    - name: test
      run: |
        echo "${{matrix.dockerfiles}}"

    
